export const LOGIN_REQUEST = `LOGIN_REQUEST`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;

export const REGISTER_REQUEST = `REGISTER_REQUEST`;
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`;

export const GET_USER_DETAILS_REQUEST = `GET_USER_DETAILS_REQUEST`;
export const GET_USER_DETAILS_SUCCESS = `GET_USER_DETAILS_SUCCESS`;

export const RESEND_VERIFY_EMAIL = `RESEND_VERIFY_EMAIL`;
