export const CREATE_EXPENSE_REQUEST = `CREATE_EXPENSE_REQUEST`;
export const CREATE_EXPENSE_SUCCESS = `CREATE_EXPENSE_SUCCESS`;

export const GET_EXPENSE_REQUEST = `GET_EXPENSE_REQUEST`;
export const GET_EXPENSE_SUCCESS = `GET_EXPENSE_SUCCESS`;

export const GET_ALL_EXPENSES_REQUEST = `GET_ALL_EXPENSES_REQUEST`;
export const GET_ALL_EXPENSES_SUCCESS = `GET_ALL_EXPENSES_SUCCESS`;

export const UPDATE_EXPENSE_REQUEST = `UPDATE_EXPENSE_REQUEST`;
export const UPDATE_EXPENSE_SUCCESS = `UPDATE_EXPENSE_SUCCESS`;
export const UPDATE_EXPENSE_FAIL = `UPDATE_EXPENSE_FAIL`;

export const DELETE_EXPENSE_REQUEST = `DELETE_EXPENSE_REQUEST`;
export const DELETE_EXPENSE_SUCCESS = `DELETE_EXPENSE_SUCCESS`;
